float:
  any:
    - base_args: ["@metric", "@dimension"]
      constructor: MilvusIVFFLAT
      disabled: true
      module: algorithms.milvus
      name: milvus-ivfflat
      run_groups:
        IVFFLAT:
          args:
            nlist: [128, 256, 512, 1024, 2048]
          query_args: [[1, 10, 20, 50, 100]]
    - base_args: ["@metric", "@dimension"]
      constructor: MilvusIVFSQ8
      disabled: true
      module: algorithms.milvus
      name: milvus-ivfsq8
      run_groups:
        IVFSQ8:
          args:
            nlist: [128, 256, 512, 1024, 2048]
          query_args: [[1, 10, 20, 50, 100]]
    - base_args: ["@metric", "@dimension"]
      constructor: MilvusIVFPQ
      disabled: true
      module: algorithms.milvus
      name: milvus-ivfpq
      run_groups:
        IVFPQ:
          args:
            nlist: [128, 256, 512, 1024, 2048]
            m: [8]
          query_args: [[1, 10, 20, 50, 100]]
    - base_args: ["@metric", "@dimension"]
      constructor: MilvusHNSW
      disabled: false
      module: algorithms.milvus
      name: milvus-hnsw
      run_groups:
        M-24:
          arg_groups: [{M: 24, efConstruction: 200}]
          args: {}
          query_args: [[50, 100, 200, 400]]
