float:
  any:
  - base_args: ['@metric']
    constructor: PGVector
    disabled: true
    module: algorithms.pgvector
    name: pgvector-hnsw
    run_groups:
      base:
        args: [ [ 24 ], [200] ]
        query_args: [ [ 50, 100, 200, 400 ] ]