float:
  any:
  - base_args: [ '@metric' ]
    constructor: OceanBaseHnswVector
    disabled: false
    module: algorithms.oceanbase
    name: oceanbase-hnsw
    run_groups:
      base:
        args: [ [ 24 ], [200] ]
        query_args: [ [ 500, 100, 200, 400 ] ]
