float:
  any:
  - base_args: ['@metric']
    constructor: OpengaussHuaweiVector
    disabled: true
    module: algorithms.opengauss-huawei
    name: opengauss-huawei-hnsw
    run_groups:
      base:
        args: [ [ 24 ], [200] ]
        query_args: [ [ 50, 100, 200, 400 ] ]